<?php

namespace App\Modules\IdentityAccess\Enums;

enum PermissionName: string
{
    case ProfileView = 'profile.view';
    case ProfileUpdate = 'profile.update';
    case AccountRequestDeletion = 'account.requestDeletion';
    case SecuritySessionsViewOwn = 'security.sessions.viewOwn';
    case SecurityDevicesViewOwn = 'security.devices.viewOwn';
    case SecurityLogsView = 'security.logs.view';
    case SecurityEventsView = 'security.events.view';
    case UsersViewAny = 'users.viewAny';
    case UsersView = 'users.view';
    case UsersCreate = 'users.create';
    case UsersCreateAdmin = 'users.createAdmin';
    case UsersCreateSuperAdmin = 'users.createSuperAdmin';
    case UsersUpdate = 'users.update';
    case UsersDeactivate = 'users.deactivate';
    case UsersRestore = 'users.restore';
    case UsersAssignRoles = 'users.assignRoles';
    case UsersAssignPermissions = 'users.assignPermissions';
    case UsersPasswordReset = 'users.passwordReset';
    case StaffCreate = 'staff.create';
    case StaffViewAny = 'staff.viewAny';
    case StaffUpdate = 'staff.update';
    case StaffDeactivate = 'staff.deactivate';
    case RolesView = 'roles.view';
    case RolesUpdate = 'roles.update';
    case PermissionsView = 'permissions.view';
    case PermissionsUpdate = 'permissions.update';
    case AdminAccess = 'admin.access';
    case SuperAdminAccess = 'superadmin.access';
    case ProtectedDownloadsAccess = 'downloads.protected.access';
    case CommentsCreate = 'comments.create';
    case CommentsViewAny = 'comments.viewAny';
    case CommentsModerate = 'comments.moderate';
    case ModerationHiddenManage = 'moderation.hidden.manage';
    case ModerationNotesView = 'moderation.notes.view';
    case RequestsCreate = 'requests.create';
    case RequestsViewOwn = 'requests.viewOwn';
    case RequestsViewAny = 'requests.viewAny';
    case RequestsUpdateStatus = 'requests.updateStatus';
    case RequestsCommentInternal = 'requests.commentInternal';
    case RequestsCommentPublic = 'requests.commentPublic';
    case RequestsFilesDownload = 'requests.files.download';
    case RequestsStatusesManage = 'requests.statuses.manage';
    case RequestsAuditView = 'requests.audit.view';
    case CmsPagesView = 'cms.pages.view';
    case CmsPagesCreate = 'cms.pages.create';
    case CmsPagesUpdate = 'cms.pages.update';
    case CmsPagesDelete = 'cms.pages.delete';
    case CmsPagesCompose = 'cms.pages.compose';
    case CmsPagesReorderBlocks = 'cms.pages.reorder_blocks';
    case CmsPagesUseReusableBlocks = 'cms.pages.use_reusable_blocks';
    case CmsPagesUseAdvancedBlocks = 'cms.pages.use_advanced_blocks';
    case CmsPagesManageHomepage = 'cms.pages.manage_homepage';
    case CmsPagesManageSystemPages = 'cms.pages.manage_system_pages';
    case CmsPagesPreview = 'cms.pages.preview';
    case CmsPagesSubmitReview = 'cms.pages.submit_review';
    case CmsPagesApprove = 'cms.pages.approve';
    case CmsPagesReject = 'cms.pages.reject';
    case CmsPagesPublish = 'cms.pages.publish';
    case CmsPagesSchedule = 'cms.pages.schedule';
    case CmsPagesArchive = 'cms.pages.archive';
    case CmsPagesRestore = 'cms.pages.restore';
    case CmsBlocksViewDefinitions = 'cms.blocks.view_definitions';
    case CmsBlocksManageDefinitions = 'cms.blocks.manage_definitions';
    case CmsBlocksManageReusable = 'cms.blocks.manage_reusable';
    case CmsBlocksUseApprovedOnly = 'cms.blocks.use_approved_only';
    case CmsSeoManage = 'cms.seo.manage';
    case CmsAuditView = 'cms.audit.view';
    case CmsApprovalsViewQueue = 'cms.approvals.view_queue';
    case CmsApprovalsAct = 'cms.approvals.act';
    case CmsPreviewAccessShared = 'cms.preview.access_shared';
    case ProductsView = 'products.view';
    case ProductsCreate = 'products.create';
    case ProductsUpdate = 'products.update';
    case ProductsPreview = 'products.preview';
    case ProductsSubmitReview = 'products.submit_review';
    case ProductsApprove = 'products.approve';
    case ProductsReject = 'products.reject';
    case ProductsPublish = 'products.publish';
    case ProductsSchedule = 'products.schedule';
    case ProductsArchive = 'products.archive';
    case ProductCategoriesManage = 'products.categories.manage';
    case ProductTagsManage = 'products.tags.manage';
    case ProductReviewsModerate = 'products.reviews.moderate';
    case BlogView = 'blog.view';
    case BlogCreate = 'blog.create';
    case BlogUpdate = 'blog.update';
    case BlogPreview = 'blog.preview';
    case BlogSubmitReview = 'blog.submit_review';
    case BlogApprove = 'blog.approve';
    case BlogReject = 'blog.reject';
    case BlogPublish = 'blog.publish';
    case BlogSchedule = 'blog.schedule';
    case BlogArchive = 'blog.archive';
    case BlogCategoriesManage = 'blog.categories.manage';
    case BlogTagsManage = 'blog.tags.manage';
    case FaqView = 'faq.view';
    case FaqCreate = 'faq.create';
    case FaqUpdate = 'faq.update';
    case FaqSubmitReview = 'faq.submit_review';
    case FaqApprove = 'faq.approve';
    case FaqReject = 'faq.reject';
    case FaqPublish = 'faq.publish';
    case FaqSchedule = 'faq.schedule';
    case FaqArchive = 'faq.archive';
    case FaqCategoriesManage = 'faq.categories.manage';
    case CareersView = 'careers.view';
    case CareersCreate = 'careers.create';
    case CareersUpdate = 'careers.update';
    case CareersSubmitReview = 'careers.submit_review';
    case CareersApprove = 'careers.approve';
    case CareersReject = 'careers.reject';
    case CareersPublish = 'careers.publish';
    case CareersSchedule = 'careers.schedule';
    case CareersArchive = 'careers.archive';
    case CareersApplicationsView = 'careers.applications.view';
    case CareersApplicationsUpdate = 'careers.applications.update';
    case CareersApplicationsNotesManage = 'careers.applications.notes.manage';
    case CareersApplicationsFilesView = 'careers.applications.files.view';
    case ShowcaseTestimonialsManage = 'showcase.testimonials.manage';
    case ShowcasePartnersManage = 'showcase.partners.manage';
    case ShowcaseTeamManage = 'showcase.team.manage';
    case ShowcaseTimelineManage = 'showcase.timeline.manage';
    case ShowcaseAchievementsManage = 'showcase.achievements.manage';
    case ShowcaseSubmitReview = 'showcase.submit_review';
    case ShowcaseApprove = 'showcase.approve';
    case ShowcaseReject = 'showcase.reject';
    case ShowcasePublish = 'showcase.publish';
    case ShowcaseSchedule = 'showcase.schedule';
    case ShowcaseArchive = 'showcase.archive';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
