<?php

use App\Modules\Pages\Enums\BlockEditorMode;

return [
    'reserved_paths' => [
        'admin',
        'account',
        'dashboard',
        'login',
        'logout',
        'register',
        'verify-email',
        'email',
        'password',
        'forgot-password',
        'reset-password',
        'up',
    ],

    'preview' => [
        'ttl_minutes' => (int) env('USNSOFT_PREVIEW_TTL_MINUTES', 30),
    ],

    'cache' => [
        'enabled' => (bool) env('USNSOFT_CMS_CACHE_ENABLED', true),
        'ttl_minutes' => (int) env('USNSOFT_CMS_CACHE_TTL_MINUTES', 15),
    ],

    'rich_text' => [
        'allowed_tags' => '<p><br><strong><em><u><ul><ol><li><blockquote><a><h2><h3><h4><hr>',
        'allowed_link_schemes' => ['http', 'https', 'mailto', 'tel'],
    ],

    'video' => [
        'providers' => ['youtube', 'vimeo', 'loom'],
    ],

    'layout_tokens' => [
        'container_width' => ['contained', 'wide', 'full'],
        'theme_variant' => ['light', 'dark', 'brand', 'accent', 'neutral'],
        'spacing' => ['none', 'sm', 'md', 'lg', 'xl'],
        'text_alignment' => ['left', 'center', 'right'],
        'card_style' => ['flat', 'elevated', 'bordered'],
        'media_position' => ['left', 'right', 'top', 'background'],
        'animation_style' => ['none', 'fade', 'slide-up', 'scale-subtle'],
        'background_type' => ['none', 'solid', 'image', 'gradient'],
        'overlay_intensity' => ['none', 'subtle', 'medium', 'strong'],
    ],

    'definitions' => [
        'hero' => [
            'name' => 'Hero',
            'category' => 'layout',
            'description' => 'Headline-first hero section with actions.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.hero',
            'default_data' => [
                'eyebrow' => 'USNsoft Platform',
                'title' => 'Software, networking, and security solutions built for scale.',
                'subtitle' => 'One trusted delivery partner from planning to operations.',
                'body' => 'Delivering dependable engineering outcomes for startups and enterprises.',
                'primary_cta_label' => 'Request Consultation',
                'primary_cta_url' => '/client-requests/new',
                'secondary_cta_label' => 'Explore Services',
                'secondary_cta_url' => '/services',
                'badge' => null,
                'trust_items' => [],
                'background_media_id' => null,
                'mobile_background_media_id' => null,
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'brand',
                'spacing' => 'xl',
                'text_alignment' => 'left',
            ],
            'rules' => [
                'eyebrow' => ['nullable', 'string', 'max:80'],
                'title' => ['required', 'string', 'max:180'],
                'subtitle' => ['nullable', 'string', 'max:220'],
                'body' => ['nullable', 'string', 'max:1600'],
                'primary_cta_label' => ['nullable', 'string', 'max:60'],
                'primary_cta_url' => ['nullable', 'string', 'max:2048'],
                'secondary_cta_label' => ['nullable', 'string', 'max:60'],
                'secondary_cta_url' => ['nullable', 'string', 'max:2048'],
                'badge' => ['nullable', 'string', 'max:80'],
                'trust_items' => ['nullable', 'array', 'max:6'],
                'trust_items.*' => ['string', 'max:80'],
                'background_media_id' => ['nullable', 'string', 'size:26'],
                'mobile_background_media_id' => ['nullable', 'string', 'size:26'],
            ],
        ],
        'slider' => [
            'name' => 'Slider',
            'category' => 'layout',
            'description' => 'Hero-like slideshow with curated slides.',
            'editor_mode' => BlockEditorMode::Advanced->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.slider',
            'default_data' => [
                'title' => 'Highlights',
                'slides' => [],
            ],
            'default_layout' => [
                'container_width' => 'full',
                'theme_variant' => 'dark',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:120'],
                'slides' => ['required', 'array', 'min:1', 'max:8'],
                'slides.*.title' => ['required', 'string', 'max:160'],
                'slides.*.subtitle' => ['nullable', 'string', 'max:180'],
                'slides.*.body' => ['nullable', 'string', 'max:1200'],
                'slides.*.cta_label' => ['nullable', 'string', 'max:60'],
                'slides.*.cta_url' => ['nullable', 'string', 'max:2048'],
                'slides.*.image_media_id' => ['nullable', 'string', 'size:26'],
                'slides.*.overlay' => ['nullable', 'in:none,subtle,medium,strong'],
            ],
        ],
        'cta' => [
            'name' => 'Call To Action',
            'category' => 'conversion',
            'description' => 'Focused section encouraging immediate action.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.cta',
            'default_data' => [
                'title' => 'Discuss your project with USNsoft',
                'body' => 'Share requirements and receive a practical delivery plan.',
                'primary_label' => 'Start Request',
                'primary_url' => '/client-requests/new',
                'secondary_label' => null,
                'secondary_url' => null,
                'supporting_note' => null,
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'accent',
                'spacing' => 'lg',
                'text_alignment' => 'center',
            ],
            'rules' => [
                'title' => ['required', 'string', 'max:180'],
                'body' => ['nullable', 'string', 'max:1200'],
                'primary_label' => ['required', 'string', 'max:60'],
                'primary_url' => ['required', 'string', 'max:2048'],
                'secondary_label' => ['nullable', 'string', 'max:60'],
                'secondary_url' => ['nullable', 'string', 'max:2048'],
                'supporting_note' => ['nullable', 'string', 'max:200'],
            ],
        ],
        'rich_text' => [
            'name' => 'Rich Text',
            'category' => 'content',
            'description' => 'Sanitized editorial text content.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.rich-text',
            'default_data' => [
                'content_html' => '<p>Add your content here.</p>',
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'light',
                'spacing' => 'md',
            ],
            'rules' => [
                'content_html' => ['required', 'string', 'max:40000'],
            ],
        ],
        'image_gallery' => [
            'name' => 'Image Gallery',
            'category' => 'media',
            'description' => 'Grid-based media gallery with captions.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.image-gallery',
            'default_data' => [
                'title' => null,
                'items' => [],
                'gallery_style' => 'grid',
                'lightbox_enabled' => true,
                'columns' => 3,
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'light',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:120'],
                'items' => ['required', 'array', 'min:1', 'max:24'],
                'items.*.media_id' => ['required', 'string', 'size:26'],
                'items.*.caption' => ['nullable', 'string', 'max:255'],
                'gallery_style' => ['nullable', 'in:grid,masonry,carousel'],
                'lightbox_enabled' => ['boolean'],
                'columns' => ['nullable', 'integer', 'min:1', 'max:4'],
            ],
        ],
        'video_embed' => [
            'name' => 'Video Embed',
            'category' => 'media',
            'description' => 'Allowlisted external video embed.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.video-embed',
            'default_data' => [
                'provider' => 'youtube',
                'video_url' => null,
                'title' => null,
                'caption' => null,
                'poster_media_id' => null,
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'dark',
                'spacing' => 'lg',
            ],
            'rules' => [
                'provider' => ['required', 'in:youtube,vimeo,loom'],
                'video_url' => ['required', 'string', 'max:2048'],
                'title' => ['nullable', 'string', 'max:160'],
                'caption' => ['nullable', 'string', 'max:500'],
                'poster_media_id' => ['nullable', 'string', 'size:26'],
            ],
        ],
        'feature_grid' => [
            'name' => 'Feature Grid',
            'category' => 'content',
            'description' => 'Feature highlights with optional links.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.feature-grid',
            'default_data' => [
                'title' => null,
                'intro' => null,
                'items' => [],
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'neutral',
                'spacing' => 'lg',
                'card_style' => 'elevated',
                'columns' => 3,
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'items' => ['required', 'array', 'min:1', 'max:12'],
                'items.*.title' => ['required', 'string', 'max:120'],
                'items.*.body' => ['nullable', 'string', 'max:500'],
                'items.*.icon' => ['nullable', 'string', 'max:60'],
                'items.*.media_id' => ['nullable', 'string', 'size:26'],
                'items.*.link' => ['nullable', 'string', 'max:2048'],
            ],
        ],
        'product_grid' => [
            'name' => 'Product Grid',
            'category' => 'integration',
            'description' => 'Curated product teaser list.',
            'editor_mode' => BlockEditorMode::Advanced->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.product-grid',
            'default_data' => [
                'title' => 'Products',
                'intro' => null,
                'source_mode' => 'featured',
                'product_ids' => [],
                'item_limit' => 6,
                'show_price' => false,
                'show_platforms' => true,
                'show_cta' => true,
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'light',
                'spacing' => 'lg',
                'card_style' => 'bordered',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'source_mode' => ['required', 'in:manual,featured,newest,category'],
                'product_ids' => ['nullable', 'array', 'max:24'],
                'product_ids.*' => ['integer', 'min:1'],
                'item_limit' => ['nullable', 'integer', 'min:1', 'max:24'],
                'show_price' => ['boolean'],
                'show_platforms' => ['boolean'],
                'show_cta' => ['boolean'],
            ],
        ],
        'testimonial_list' => [
            'name' => 'Testimonial List',
            'category' => 'social-proof',
            'description' => 'Testimonials in cards or slider view.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.testimonial-list',
            'default_data' => [
                'title' => 'What clients say',
                'intro' => null,
                'source_mode' => 'manual',
                'items' => [],
                'item_limit' => 6,
                'layout_style' => 'cards',
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'light',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'source_mode' => ['required', 'in:manual,featured,recent'],
                'items' => ['nullable', 'array', 'max:20'],
                'items.*.author' => ['required_with:items', 'string', 'max:120'],
                'items.*.quote' => ['required_with:items', 'string', 'max:1000'],
                'items.*.role' => ['nullable', 'string', 'max:120'],
                'item_limit' => ['nullable', 'integer', 'min:1', 'max:20'],
                'layout_style' => ['nullable', 'in:cards,slider,grid'],
            ],
        ],
        'partner_logos' => [
            'name' => 'Partner Logos',
            'category' => 'social-proof',
            'description' => 'Partner and client logo strip.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.partner-logos',
            'default_data' => [
                'title' => null,
                'items' => [],
                'grayscale' => true,
                'link_enabled' => false,
                'auto_scroll' => false,
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'neutral',
                'spacing' => 'md',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:120'],
                'items' => ['required', 'array', 'min:1', 'max:24'],
                'items.*.media_id' => ['required', 'string', 'size:26'],
                'items.*.name' => ['nullable', 'string', 'max:120'],
                'items.*.url' => ['nullable', 'string', 'max:2048'],
                'grayscale' => ['boolean'],
                'link_enabled' => ['boolean'],
                'auto_scroll' => ['boolean'],
            ],
        ],
        'timeline' => [
            'name' => 'Timeline',
            'category' => 'content',
            'description' => 'Milestone timeline component.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.timeline',
            'default_data' => [
                'title' => null,
                'intro' => null,
                'items' => [],
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'light',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'items' => ['required', 'array', 'min:1', 'max:20'],
                'items.*.date' => ['nullable', 'string', 'max:30'],
                'items.*.title' => ['required', 'string', 'max:160'],
                'items.*.body' => ['nullable', 'string', 'max:1000'],
                'items.*.media_id' => ['nullable', 'string', 'size:26'],
            ],
        ],
        'team_cards' => [
            'name' => 'Team Cards',
            'category' => 'company',
            'description' => 'Team profiles with role and bio.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.team-cards',
            'default_data' => [
                'title' => null,
                'intro' => null,
                'items' => [],
                'layout_style' => 'cards',
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'light',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'items' => ['required', 'array', 'min:1', 'max:20'],
                'items.*.name' => ['required', 'string', 'max:120'],
                'items.*.role' => ['nullable', 'string', 'max:120'],
                'items.*.bio' => ['nullable', 'string', 'max:600'],
                'items.*.image_media_id' => ['nullable', 'string', 'size:26'],
                'items.*.profile_url' => ['nullable', 'string', 'max:2048'],
                'layout_style' => ['nullable', 'in:cards,list,minimal'],
            ],
        ],
        'faq_list' => [
            'name' => 'FAQ List',
            'category' => 'support',
            'description' => 'Frequently asked questions section.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.faq-list',
            'default_data' => [
                'title' => 'Frequently asked questions',
                'intro' => null,
                'items' => [],
                'searchable' => false,
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'neutral',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'items' => ['required', 'array', 'min:1', 'max:50'],
                'items.*.question' => ['required', 'string', 'max:280'],
                'items.*.answer' => ['required', 'string', 'max:5000'],
                'searchable' => ['boolean'],
            ],
        ],
        'stat_counters' => [
            'name' => 'Stat Counters',
            'category' => 'social-proof',
            'description' => 'Numeric achievements and counters.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.stat-counters',
            'default_data' => [
                'title' => null,
                'stats' => [],
                'animate' => true,
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'dark',
                'spacing' => 'lg',
                'columns' => 4,
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:120'],
                'stats' => ['required', 'array', 'min:1', 'max:8'],
                'stats.*.number' => ['required', 'numeric', 'min:0'],
                'stats.*.label' => ['required', 'string', 'max:120'],
                'stats.*.prefix' => ['nullable', 'string', 'max:12'],
                'stats.*.suffix' => ['nullable', 'string', 'max:12'],
                'stats.*.description' => ['nullable', 'string', 'max:300'],
                'animate' => ['boolean'],
            ],
        ],
        'contact_section' => [
            'name' => 'Contact Section',
            'category' => 'conversion',
            'description' => 'Business contact and optional request form panel.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.contact-section',
            'default_data' => [
                'title' => 'Contact USNsoft',
                'intro' => null,
                'address' => null,
                'phone' => null,
                'email' => null,
                'hours' => null,
                'whatsapp_url' => null,
                'telegram_url' => null,
                'map_mode' => 'disabled',
                'map_url' => null,
                'show_form' => true,
                'form_type' => 'contact',
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'neutral',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'address' => ['nullable', 'string', 'max:500'],
                'phone' => ['nullable', 'string', 'max:60'],
                'email' => ['nullable', 'email:rfc,dns'],
                'hours' => ['nullable', 'string', 'max:255'],
                'whatsapp_url' => ['nullable', 'url', 'max:2048'],
                'telegram_url' => ['nullable', 'url', 'max:2048'],
                'map_mode' => ['nullable', 'in:disabled,embed,placeholder'],
                'map_url' => ['nullable', 'url', 'max:2048'],
                'show_form' => ['boolean'],
                'form_type' => ['nullable', 'in:contact,general_inquiry,project_inquiry,newsletter'],
            ],
        ],
        'form_block' => [
            'name' => 'Form Block',
            'category' => 'conversion',
            'description' => 'References internal safe form handlers.',
            'editor_mode' => BlockEditorMode::Advanced->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.form-block',
            'default_data' => [
                'form_type' => 'contact',
                'title' => 'Send us a message',
                'intro' => null,
                'success_message' => 'Thank you. We will get back to you soon.',
                'anti_spam_enabled' => true,
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'light',
                'spacing' => 'lg',
            ],
            'rules' => [
                'form_type' => ['required', 'in:contact,general_inquiry,project_inquiry,newsletter'],
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:600'],
                'success_message' => ['nullable', 'string', 'max:500'],
                'anti_spam_enabled' => ['boolean'],
            ],
        ],
        'file_download_block' => [
            'name' => 'File Download Block',
            'category' => 'conversion',
            'description' => 'Managed file links with optional auth guard.',
            'editor_mode' => BlockEditorMode::Advanced->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.file-download-block',
            'default_data' => [
                'title' => null,
                'body' => null,
                'files' => [],
            ],
            'default_layout' => [
                'container_width' => 'contained',
                'theme_variant' => 'neutral',
                'spacing' => 'md',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'body' => ['nullable', 'string', 'max:500'],
                'files' => ['required', 'array', 'min:1', 'max:30'],
                'files.*.media_id' => ['required', 'string', 'size:26'],
                'files.*.label' => ['required', 'string', 'max:160'],
                'files.*.access_mode' => ['nullable', 'in:public,protected'],
                'files.*.require_login' => ['boolean'],
            ],
        ],
        'blog_teaser' => [
            'name' => 'Blog Teaser',
            'category' => 'integration',
            'description' => 'Latest or curated blog teaser list.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.blog-teaser',
            'default_data' => [
                'title' => 'Latest insights',
                'intro' => null,
                'source_mode' => 'latest',
                'item_limit' => 3,
                'show_excerpt' => true,
                'show_image' => true,
                'show_date' => true,
                'show_author' => true,
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'light',
                'spacing' => 'lg',
                'card_style' => 'bordered',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'source_mode' => ['required', 'in:latest,category,tags,manual'],
                'item_limit' => ['nullable', 'integer', 'min:1', 'max:12'],
                'show_excerpt' => ['boolean'],
                'show_image' => ['boolean'],
                'show_date' => ['boolean'],
                'show_author' => ['boolean'],
            ],
        ],
        'services_block' => [
            'name' => 'Services Block',
            'category' => 'integration',
            'description' => 'Services teaser cards and CTA.',
            'editor_mode' => BlockEditorMode::Basic->value,
            'is_reusable_allowed' => true,
            'rendering_view' => 'components.blocks.services-block',
            'default_data' => [
                'title' => 'Services',
                'intro' => null,
                'source_mode' => 'featured',
                'service_ids' => [],
                'card_style' => 'elevated',
                'cta_label' => 'View all services',
                'cta_url' => '/services',
            ],
            'default_layout' => [
                'container_width' => 'wide',
                'theme_variant' => 'neutral',
                'spacing' => 'lg',
            ],
            'rules' => [
                'title' => ['nullable', 'string', 'max:160'],
                'intro' => ['nullable', 'string', 'max:500'],
                'source_mode' => ['required', 'in:manual,featured,category'],
                'service_ids' => ['nullable', 'array', 'max:24'],
                'service_ids.*' => ['integer', 'min:1'],
                'card_style' => ['nullable', 'in:flat,elevated,bordered'],
                'cta_label' => ['nullable', 'string', 'max:60'],
                'cta_url' => ['nullable', 'string', 'max:2048'],
            ],
        ],
    ],
];
